// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAOhJCrSXAgpObwVtD9CssDgYvFk6lPlqI',
    appId: '1:147483688957:web:56fafdac01023f16cce394',
    messagingSenderId: '147483688957',
    projectId: 'elmanfy-244f3',
    authDomain: 'elmanfy-244f3.firebaseapp.com',
    storageBucket: 'elmanfy-244f3.firebasestorage.app',
    measurementId: 'G-V29Z9MRRY5',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyATxCBFqvw1IZy0xYbOXAgzxSZk71NiKkk',
    appId: '1:147483688957:android:620444dae2d11ac3cce394',
    messagingSenderId: '147483688957',
    projectId: 'elmanfy-244f3',
    storageBucket: 'elmanfy-244f3.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCfbTUVOO8aEAFVK8vZMWueS5VHKyTJFik',
    appId: '1:147483688957:ios:bcfd85511a1c89e2cce394',
    messagingSenderId: '147483688957',
    projectId: 'elmanfy-244f3',
    storageBucket: 'elmanfy-244f3.firebasestorage.app',
    iosBundleId: 'com.example.elmanfy',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCfbTUVOO8aEAFVK8vZMWueS5VHKyTJFik',
    appId: '1:147483688957:ios:bcfd85511a1c89e2cce394',
    messagingSenderId: '147483688957',
    projectId: 'elmanfy-244f3',
    storageBucket: 'elmanfy-244f3.firebasestorage.app',
    iosBundleId: 'com.example.elmanfy',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAOhJCrSXAgpObwVtD9CssDgYvFk6lPlqI',
    appId: '1:147483688957:web:ea1a976dd96593cacce394',
    messagingSenderId: '147483688957',
    projectId: 'elmanfy-244f3',
    authDomain: 'elmanfy-244f3.firebaseapp.com',
    storageBucket: 'elmanfy-244f3.firebasestorage.app',
    measurementId: 'G-KRMQ7VXL2J',
  );
}
